### ISSUE TITLE
Can I use this outside LMS?

### ISSUE THREAD

**Issue by ediboy** [RusticiSoftware/cmi5.js#2]
Good day,

First of all thank you for a great plugin. I just wanted to ask if I can use this outside the LMS. I have LRS setup. What are the things to consider or additional setup?

Thanks,
Ediboy

**Comment by brianjmiller** [comment]
Sorry just now saw this while going through another issue.

I can't quite tell if you mean this library or cmi5 in general. cmi5 itself relies on cooperation between the launching system (effectively an LMS) and the content or AU (assignable unit) so both halves of that equation must be fulfilled. This library is intended for the implementation of the AU during runtime, so in that sense it is outside of an LMS, but ultimately the AU would need to be launched to leverage this library (it could be a server side JavaScript AU if that helps at all).
